// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siojarsutauhnuiwrmkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpb2phcnN1dGF1aG51aXdybWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQwMzQsImV4cCI6MjA2NTQ5MDAzNH0.41cAWvFl7aKxLVF1QjYxIpK7AR4m3xaPZBtcmcI2g8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);